spring:
  profiles:
    include: config
    active: dev
    default: dev
  test:
    database:
      replace: NONE
  messages:
    basename: messages
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        format_sql: 'true'
        use_sql_comments: 'true'
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: 'true'
    open-in-view: 'true'
    defer-datasource-initialization: true

    #Method Put,Delete ??? ?? ??
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
    #???? ??
  thymeleaf:
    cache: 'false'
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    enabled: 'true'
    #Devtools??
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'

  servlet:
    multipart:
      enabled: 'true'
      max-file-size: 10MB
      max-request-size: 30MB
  output:
    ansi:
      enabled: always
server:
  port: '8092'
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
file:
  Upfolder: file:///ImgList/SportTeam/
  Upimg: C:/ImgList/SportTeam/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      password: '1111'
      username: root
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/sport?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      connection-test-query: SELECT NOW() FROM dual


---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      password: '1111'
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      connection-test-query: SELECT NOW() FROM dual

---


