spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 922405067379-s6hqmtorgvp0cibhs0t7gbvg257irbah.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: DGZfFjNzCXL8jyQarIYO
            client-secret: CS06vo6407
            client-name: Naver
            redirect-uri: http://localhost:8091/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          kakao:
            client-id: b59d9f1d1d9da1991b8d0cb936b730e2
            client-secret: Q5q6z1VLyci3auWc9eGn4p0zms0Njn35
            client-name: Kakao
            redirect-uri: http://localhost:8091/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#scope 기본값은 email, profile, openid 인데 profile, email만 입력한 이유는
#※ openid가 있으면 OpenId Provider로 인식하기 때문인데, 이렇게 되면 OpenId Provider인 서비스와 그렇지 않은 서비스(네이버/카카오 등)로 나눠서 각각 OAuth2Service를 만들어야 한다.